Defined activation parameters for technical specification.
SoftwareVerde/bitcoin-cash-chips pull request #5
Opened 2021-04-05 19:58 UTC by joshmg

2021-04-05 20:11 UTC, BigBlockIfTrue commented
Looks OK to me.

I think it would be nice if the CHIP also says a few sentences about how BCHU (CPFP) and BCHN (no CPFP) handle large chains, with the reference to Peter Tschipper's document for BCHU. Calin Culianu can give you some sentences for BCHN.

2021-04-05 20:49 UTC, ftrader commented on unconfirmed-transaction-chain-limit.md
> +The current policy limit of 50 on unconfirmed ancestors or descendants is to be removed entirely once MTP >= 1621080000 and this limit removal remains in affect even in the case of a subsequent re-or
```suggestion
The current policy limit of 50 unconfirmed ancestors or descendants is to be removed entirely once MTP >= 1621080000 and this limit removal remains in affect even in the case of a subsequent re-org to below that MTP.
```

I removed the superfluous 'on' which I accidentally added in my [BCR comment](https://bitcoincashresearch.org/t/chip-unconfirmed-transaction-chain-limit/302/48?u=freetrader).

2021-04-05 20:50 UTC, ftrader requested changes
Just a small typo found (was my fault in the original, my wording was just bad there)

2021-04-06 00:16 UTC, joshmg commented
> Looks OK to me.
> 
> I think it would be nice if the CHIP also says a few sentences about how BCHU (CPFP) and BCHN (no CPFP) handle large chains, with the reference to Peter Tschipper's document for BCHU. Calin Culianu can give you some sentences for BCHN.

I'll see if I can't reach them tomorrow for these additions.  Thanks, BBiT.

2021-04-06 17:21 UTC, joshmg commented
I'm going to merge this change as-is for now and contact Calin and Stone separately from this PR to add additional content.

2021-04-06 17:21 UTC, merged